services:
  playwright-server:
    ## Change also the start script below!!!
    image: mcr.microsoft.com/playwright:v1.56.1-noble 
    container_name: playwright-server
    cpus: 2
    init: true
    tty: true
    user: pwuser
    working_dir: /home/pwuser
    ports:
      - "3001:3000"
    extra_hosts:
      - "hostmachine:host-gateway"
    command: >
      /bin/sh -c "npx -y playwright@1.56 run-server --port 3000 --host 0.0.0.0"